### ISSUE TITLE
How to use this framework in api layer?

### ISSUE THREAD

**Issue by h-fathi** [draphyz/DDD#1]
Hi
First of all, thank you for the framework you wrote.
I had a question how to inject and use it?

**Comment by draphyz** [comment]
Hi,
Your question is difficult because it depends on your software architecture. But I advice you to centralize and test the code of your application layer in libraries as in my example and to use a dependency injection library in your application to configure your command and query handlers. Then you can use and create commands and queries in your controller or presenter and process these commands and queries with a query or command processor based on dependency injection (you can find [here](https://github.com/draphyz/DDD/blob/entityframework/Src/DDD.Core/Application/CommandProcessor.cs) an implementation of a command processor based on dependency injection). In a microservices architecture, commands, queries and results of queries are just DTOs used in the API of a microservice. This API is fine-grained and is often not exposed to your client but used by an API gateway that defines a coarse-grained API adapted to your client's needs.

**Comment by h-fathi** [comment]
Thank you for answer,
I working on your sample project "HealthcareDelivery" and I've trouble injecting dependency into the API layer. Would you please make API layer for "HealthcareDelivery" project and inject dependency or help me make it.

Thanks in advance

**Comment by draphyz** [comment]
Hi,

It's a good idea. I've already thought about it but I don't have time at the moment to implement it. I will do it soon. You can get inspired by this chunk of code using SimpleInjector : 

```csharp
var assemblies = GetAssembliesToScan();
container.Register(typeof(IMappingProcessor), () => new MappingProcessor(container));
container.Register(typeof(ICommandProcessor), () => new CommandProcessor(container));
container.Register(typeof(IQueryProcessor), () => new QueryProcessor(container));
container.Register(typeof(IEventPublisher), () => new EventPublisher());
container.Register(typeof(ICommandHandler<>), assemblies);
container.Register(typeof(IQueryHandler<,>), assemblies);
container.Register(typeof(ICommandValidator<>), typeof(FluentCommandValidatorAdapter<>));
container.Register(typeof(IQueryValidator<>), typeof(FluentQueryValidatorAdapter<>));
container.Register(typeof(IValidator<>), assemblies);
container.Register(typeof(IRepository<>), assemblies);
container.Register(typeof(IObjectTranslator<,>), assemblies);
container.Register(typeof(IObjectMapper<,>), assemblies);
```
